config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :carts
    resources :line_items
    resources :orders
    resources :products

    root to: "users#index"
  end

  devise_for :users
  get 'admin' => 'admin#index'

  resources :products do
    get :who_bought, on: :member
  end

  get 'users' => 'users#index'
  get 'users/new' => 'users#new'
  post 'users/create_user' => 'users#create'
  delete 'users/delete/:id' => 'users#destroy', as: :user_delete


  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end

  root 'store#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript">
        I18n.defaultLocale = "<%= I18n.default_locale %>"; 
        I18n.locale = "<%= I18n.locale %>";
    </script>
  </head>

  <body>
    <header class="main">
      <aside>
        <%= form_tag store_index_path, class: 'locale' do %>
          <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
          <%= submit_tag 'submit', id: "submit_locale_change" %>
        <% end %> 
      </aside>

      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf'%>
      <h1><%= @page_title%></h1>

      
      <% if !user_signed_in? %>
        <%= link_to "Login", new_user_session_path, :class => 'nav_link'  %>
      <% end %>

    </header>
    <section class="content">
      <nav class="side_nav">
        <% if @cart %>
          <div id="cart" class="carts">
            <%= render_if @cart && @cart.line_items.any?, @cart %> 
          </div>
        <% end %>

        <% if user_signed_in? %>
        <p class="logged_in_nav">
                Logged in as <strong><%= current_user.email %></strong>.<br/><br/>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn logout_link'  %>
        </p>
        <% end %>

        <ul>
          <li><a href="/"><%= t('.home') %></a></li>
          <li><a href="/questions"><%= t('.questions') %></a></li>
          <li><a href="/news"><%= t('.news') %></a></li>
          <li><a href="/contact"><%= t('.contact') %></a></li>
        </ul>
        <% if user_signed_in? and policy(:user).admin? %>
          <nav class="logged_in_nav">
            <ul>
              <li><%= link_to 'Orders', admin_orders_path %></li>
              <li><%= link_to 'Products', admin_products_path %></li>
              <li><%= link_to 'Users', admin_users_path %></li>
              <!-- <li><a href="/">Users</a></li> -->
            </ul>
            
          </nav>
        <% end %>
      </nav>
      <main class='<%= controller.controller_name %>'>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
      </main>
    </section>
    
  </body>
</html>